### ISSUE TITLE
The cancel [X] option on the Trivia module removes it and leaves the website blank

### ISSUE THREAD

**Issue by tamannamoharana** [danphillips-ca/danphillips-ca.github.io#9]
The cancel [X] option on the Trivia module removes it and leaves the website blank. Refreshing the page restores it though.

**Comment by danphillips-ca** [comment]
'x' removed - thanks!

I've also moved the repository. Issues can now be reported here: https://github.com/danphillips-ca/trivia-danphillips-ca/issues
